# Generated by Django 3.0.4 on 2020-04-20 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NCTId', models.TextField(verbose_name='NCT_ID')),
                ('BriefTitle', models.TextField(verbose_name='title')),
                ('BriefSummary', models.TextField(verbose_name='summary')),
                ('InterventionDescription', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True, verbose_name='intervention'), default=list, size=None)),
                ('InterventionName', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True, verbose_name='intervention-drug'), default=list, size=None)),
                ('OverallStatus', models.TextField(verbose_name='status')),
                ('CentralContactName', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True, verbose_name='contact-name'), default=list, size=None)),
                ('CentralContactEMail', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True, verbose_name='contact-email'), default=list, size=None)),
                ('CentralContactPhone', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True, verbose_name='contact-phone'), default=list, size=None)),
                ('LocationFacility', models.TextField(verbose_name='facility')),
                ('LeadSponsorName', models.TextField(verbose_name='sponsor')),
                ('LocationCity', models.TextField(blank=True, null=True, verbose_name='city')),
                ('LocationState', models.TextField(blank=True, null=True, verbose_name='state')),
                ('LocationZip', models.TextField(blank=True, null=True, verbose_name='zip-code')),
                ('LocationCountry', models.TextField(blank=True, null=True, verbose_name='country')),
                ('Latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('Longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
            ],
        ),
    ]
