# Generated by Django 3.0.4 on 2020-04-15 12:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='CentralContactEMail',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='contact-email'), size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='CentralContactName',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='contact-name'), size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='CentralContactPhone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='contact-phone'), size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='LocationCity',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='city'), size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='LocationCountry',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='country'), size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='LocationFacility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='facility'), size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='LocationState',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='state'), size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='LocationZip',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name='zip-code'), size=None),
        ),
    ]
