# Generated by Django 3.0.4 on 2020-04-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='Link',
        ),
        migrations.AddField(
            model_name='study',
            name='Visit',
            field=models.URLField(blank=True, max_length=100, verbose_name='link'),
        ),
    ]
