# Generated by Django 3.0.4 on 2020-04-28 11:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudiesAggregatedByLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('Longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('Studies', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True, verbose_name='studies'), default=list, size=None)),
            ],
        ),
    ]
