# Generated by Django 3.0.4 on 2020-04-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20200408_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='Visit',
        ),
    ]
