# Generated by Django 3.0.4 on 2020-04-15 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_auto_20200415_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='CentralContactPhone',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='contact-phone'), size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='LocationZip',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='zip-code'), size=None),
        ),
    ]
