# Generated by Django 3.0.4 on 2020-04-15 13:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20200415_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='InterventionName',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='intervention-drug'), size=None),
        ),
    ]
