version: '3'

services:
  frontend:
    image: registry.gitlab.propulsion-home.ch/covid-dashboard/dashboard:latest
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: "tail -f /dev/null"

# volumes:
#   postgresdb:

