export const BUTTON_THEME_STATE = 'BUTTON_THEME_STATE';
export const SIDEBAR_DATA = 'SIDEBAR_DATA';
export const SEARCH_DATA = 'SEARCH_DATA';
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTRATION = "USER_REGISTRATION";

