export const BUTTON_THEME_STATE = 'BUTTON_THEME_STATE';
export const SIDEBAR_DATA = 'SIDEBAR_DATA';
export const SEARCH_DATA = 'SEARCH_DATA';
export const MAP_DATA = 'MAP_DATA';
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTRATION = "USER_REGISTRATION";
export const STATUS_OPTION_DATA = "STATUS_OPTION_DATA";

